from enum import Enum


class TypeTags(str, Enum):
    AnnotatedStringTag = 'ElectionResults.AnnotatedString'
    AnnotatedUriTag = 'ElectionResults.AnnotatedUri'
    BallotCountsTag = 'ElectionResults.BallotCounts'
    BallotMeasureContestTag = 'ElectionResults.BallotMeasureContest'
    BallotMeasureSelectionTag = 'ElectionResults.BallotMeasureSelection'
    BallotStyleTag = 'ElectionResults.BallotStyle'
    CandidateTag = 'ElectionResults.Candidate'
    CandidateContestTag = 'ElectionResults.CandidateContest'
    CandidateSelectionTag = 'ElectionResults.CandidateSelection'
    ContactInformationTag = 'ElectionResults.ContactInformation'
    CountStatusTag = 'ElectionResults.CountStatus'
    DeviceClassTag = 'ElectionResults.DeviceClass'
    ElectionTag = 'ElectionResults.Election'
    ElectionReportTag = 'ElectionResults.ElectionReport'
    ExternalIdentifierTag = 'ElectionResults.ExternalIdentifier'
    HoursTag = 'ElectionResults.Hours'
    InternationalizedTextTag = 'ElectionResults.InternationalizedText'
    LanguageStringTag = 'ElectionResults.LanguageString'
    LatLngTag = 'ElectionResults.LatLng'
    OfficeTag = 'ElectionResults.Office'
    OrderedContestTag = 'ElectionResults.OrderedContest'
    OrderedHeaderTag = 'ElectionResults.OrderedHeader'
    OtherCountsTag = 'ElectionResults.OtherCounts'
    PartyTag = 'ElectionResults.Party'
    PartyContestTag = 'ElectionResults.PartyContest'
    PartySelectionTag = 'ElectionResults.PartySelection'
    PersonTag = 'ElectionResults.Person'
    ReportingUnitTag = 'ElectionResults.ReportingUnit'
    RetentionContestTag = 'ElectionResults.RetentionContest'
    ScheduleTag = 'ElectionResults.Schedule'
    VoteCountsTag = 'ElectionResults.VoteCounts'
