from versadm.app.routers import ballot_style
from versadm.app.routers import candidate
from versadm.app.routers import contest
from versadm.app.routers import election
from versadm.app.routers import election_report
from versadm.app.routers import health
from versadm.app.routers import office
from versadm.app.routers import party
from versadm.app.routers import person
from versadm.app.routers import reporting_unit
